### ISSUE TITLE
Hyper parameter sweeping

### ISSUE THREAD

**Issue by LouisCastricato** [CarperAI/trlx#12]
We need a way to sweep over a set of hyper parameters. Maybe something like wandb sweep? @reciprocated mentioned this is very important; however, @ShivanshuPurohit has mentioned wandb sweep does not work with NeoX, so I am hesitant.

**Comment by ShivanshuPurohit** [comment]
it didn't work with neox because neox uses yamls to parse the args and sweeps create yamls themselves so we needed nested yamls dynamically created on the fly which is too much work. Fortunately there's some work done now to run hparam sweeping on neox (didn't try myself) [here](https://github.com/determined-ai/determined/blob/master/examples/deepspeed/gpt_neox/hp_search.yaml)

**Comment by reciprocated** [comment]
can we can keep neox and rl specific parameters in seperate formats perhaps?

**Comment by ShivanshuPurohit** [comment]
we could just make a `rl.yml` and pass that for neox args like [here](https://github.com/determined-ai/determined/blob/106e2313e7dd143138eab3ee0a106f5777239083/examples/deepspeed/gpt_neox/hp_search.yaml#L7)

**Comment by LouisCastricato** [comment]
Whatever we do it needs to work for BOTH the hugging face and NeoX backend

**Comment by LouisCastricato** [comment]
This issue should take a very high priority over the next week,

**Comment by ayulockin** [comment]
I think I have figured out how to use W&B sweeps with TRLX (while leveraging HF accelerate as well). I will document my findings and gotchas with a concrete example (soon)

Note that the high level process is -

* Initialize a wandb sweep. I am building hyperparameter search around `examples/ppo_sentiments.py`. Since we want to search over some range of hyperparameters I have created `configs/sweep_configs/ppo_config.yml` file. Depending on the scope of search we can write multiple sweep yml files. To initialize `wandb sweep configs/sweep_configs/ppo_config.yml` file.
* Run the sweep agent. 

To use `accelerate launch` the `command` key in the `configs/sweep_configs/ppo_config.yml` file is:

```
command:
  - ${env}
  - accelerate
  - launch
  - ${program}
  - ${args}
```

I will document it in more detail once I have figured out the best way to pass the configs selected by sweep controller.
