### ISSUE TITLE
How to implement a conditional reward?

### ISSUE THREAD

**Issue by mukhal** [CarperAI/trlx#146]
I want my reward function to depend on the prompt used. Mainly, I want to fine-tune an LM for a conditional generation task e.g., summarization. It seems that the reward function expects only a list of model outputs. How can I access the prompt used for each output sample? Any suggestions?

**Comment by reciprocated** [comment]
Hello! The reward function currently expects the whole `sample = prompt + output` as input, so in the case of summarization you could split it over "TL;DR" to recover prompts, or in a general case you could find the largest common prefix against prepared prompts. However the latter might be too complex and there's been expressed interest previously to update the signature to `reward_fn(samples, prompts, outputs)` to make it easier for a general usage, so I will add this shortly.

**Comment by James4Ever0** [comment]
In addition to the parameter allowing passing prompt-dependent reward function, I'm more interested in the way of implementing the reward function.

How is it done, to efficiently train a reward function out of a fine-tuned autoregressive model like GPT2 (cause it has seen much), perceiving both prompts and answers, then generating the reward faithfully according to the score given by human?

What if the prompt is long because we want to do few-shot dialogs? Can the reward function handle infinite input length on both prompt and answer? What if we want to talk to the bot and preserve previous context just like what ChatGPT does, requiring passing all chat histories as prompt and desired answer as input?

Pretty sure such reward function is missing in this repo, which seems to be crucial and rare to find a proper implementation compared to PPO and RLHF on language models (which I have at least seen a few)

In my opinion, if failed to implement this with current models, we can just let human be part of the reward function, score the answers according to prompts and answers (though tiresome for sure).

**Comment by James4Ever0** [comment]
To handle such wide range which ChatGPT is capable of, the reward function is either multimodal (merged with multiple metrics and models, fine-tuned according to human preference) or monolithic (must be huge, resource efficient so it could be trained from SFT or part of the RLHF model).

**Comment by jon-tow** [comment]
Hello, @James4Ever0 ! We do not plan on incorporating reward modeling into this repository. If you want to get a better idea of such fine-tuning (SFT + RMs) in practice, you should check out the amazing [reward-modeling repo](https://github.com/Dahoas/reward-modeling) created by the author of `trlx` 😄.

**Comment by mukhal** [comment]
@reciprocated is there a way now to use a reward fn of the form `reward_fn(samples, prompts, outputs)`?
