### ISSUE TITLE
different tokenizers used for SFT, Reward and RL models in Reddit TL;DR summarization task with defaut PPO_config

### ISSUE THREAD

**Issue by YingHH1** [CarperAI/trlx#325]
### 🐛 Describe the bug

Hi, 

I notice that in sft/train_gptj_summarize.py and reward_model/train_reward_model_gptj.py , the tokenizer is loaded as:

tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")

In trlx_gptj_text_summarization.py , the tokenizer for the Reward model is loaded similarly as:

rw_tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")

However, the tokenizer used in the get_prompt_dataset function in trlx_gptj_text_summarization.py is defined as:

tokenizer = AutoTokenizer.from_pretrained(config.tokenizer.tokenizer_path)

and config.tokenizer.tokenizer_path points to gpt2 tokenizer as in configs/ppo_config_summ_gptj.yml:
tokenizer:
  tokenizer_path: "gpt2"

Although, gpt-j uses the same tokenizer as GPT-2/GPT-3, but as stated on Huggingface:

_Although the embedding matrix has a size of 50400, only 50257 entries are used by the GPT-2 tokenizer. These extra tokens are added for the sake of efficiency on TPUs. To avoid the mis-match between embedding matrix size and vocab size, the tokenizer for [GPT-J](https://huggingface.co/EleutherAI/gpt-j-6B) contains 143 extra tokens <|extratoken_1|>... <|extratoken_143|>, so the vocab_size of tokenizer also becomes 50400._

Therefore, does it mean there is a inconsistency in the tokenizers across the PPO pipeline? I would appreciate it if someone can help me on understanding this tokenizer discrepancy. Many thanks!

**Comment by reciprocated** [comment]
Hi! There are no inconsistency here (algorithmically at least) because the communication with the reward model happens through raw strings, i.e. `reward_fn` accepts type `str` allowing the reward model to use arbitrary tokenizer, irregardless of the training config. It just so happens that in this example both the student and the reward model are GPT-Js, and tokenizer discrepancy shouldn't matter apart from it being a subject to https://github.com/CarperAI/trlx/issues/284
